### PR TITLE
Multi app support session preservation (#25)

### PR DESCRIPTION
**Pull request by donrestarone**
* apps tab, dynamic tabs

* added link validation

* added support for dynamic endpoints, fixed blog not refreshing

* added session preservation

### CODE REVIEW

**Comment by donrestarone** [comment]
@josessolmaximo web session preservation is not working-- how did you verify that? 

When I login to http://violet.restarone.solutions via the iOS app -- it works, but then when I close the app I have to login again

**Comment by josessolmaximo** [comment]
Did you tick the remember me checkbox? I think that's necessary.
https://user-images.githubusercontent.com/112497883/236863450-9f58435f-c5a7-40d3-aae6-b412438fdc90.mov

**Comment by donrestarone** [comment]
@josessolmaximo thanks for flagging, I'll check with option turned on. 

Is there a reason why the client doesnt hold onto the session if the checkbox isn't selected?

**Comment by donrestarone** [comment]
okay @josessolmaximo -- we will handle the default checked condition on the server-side 👍

**Pull request merged**
